; Register Main HotKeys
MH := [{"$!f": "AutoLoot"
    , "$F17": "LeftRapid"
    , "$+y": "DoClickConfirm"
    , "$+x": "DoClickClose"
    , "$!+t": "ConfirmTime"
    , "$F13": "Teleport_Mondstadt"
    , "$+F13": "Teleport_Teapot"
    , "$F14": "Teleport_Liyue"
    , "$+F14": "Teleport_TheChasm"
    , "$F15": "Teleport_Inazuma"
    , "$+F15": "Teleport_Enkanomiya"
    , "$F16": "Teleport_Sumeru"
    , "$+e": "AutoExpedition"
    , "$F18": "AutoRotation"
    , "$MButton": "AutoTeleport"
    , "$F19": "AutoSight"
    , "$h": "CraftMax"
    , "$+h": "CraftIngredientMax"
    , "$u": "ItemUpgrade"
    , "$p": "PurchaseMax"
    , "$r": "SkipDialogV2"
    , "$+v": "SkipDomainWish"
    , "$+t": "TimeMGMT"
    , "$^t": "DayTime"
    , "$!t": "EveningTime"
    , "$SC028": "LockIt"
    , "$+!^e": "ESToggle"
    , "$+!^q": "QBToggle"
    , "$XButton1": "AutoMagnet"
    , "$XButton2": "AutoMagnet"
    , "$+XButton1": "MapZoomMaxOUT"
    , "$+XButton2": "MapZoomMaxIN"
    , "$^XButton1": "MapZoomHalfOUT"
    , "$^XButton2": "MapZoomHalfIN"
    , "$SC027": "PartyOCR"
    , "$+SC029": "UpdateEquippedParty"
    , "$+SC028": "TakePartyBitmap"
    , "$+F21":"UnicoreStronk"
    , "$+F22":"UnicoreWeak"
    , "$+F23":"UnicoreReportOpts"
    , "$Numpad0":"UnicoreRapidFire"
    , "$Numpad1":"UnicoreRF1"
    , "$Numpad2":"UnicoreRF3"
    , "$Numpad3":"UnicoreRF6"
    , "$Numpad4":"UnicoreRF10"
    , "$Numpad5":"UnicoreRF15"
    , "$Numpad6":"UnicoreRF20"
    , "$Numpad7":"UnicoreRF30"
    , "$Numpad8":"UnicoreRF40"
    , "$Numpad9":"UnicoreRF50"
    , "$!Numpad0":"UnicoreAutoChests"
    , "$!Numpad1":"AutoChestsPBAOE"
    , "$!Numpad2":"AutoChestsHalf"
    , "$!Numpad3":"AutoChestsMax"
    , "$!Numpad4":"AutoTreesPBAOE"
    , "$!Numpad5":"AutoTreesHalf"
    , "$!Numpad6":"AutoTreesMax"
    , "$!NumpadDot":"UnicoreAutoTrees"
    , "$NumpadDot":"UnicoreCDReducer"
    , "$NumpadSub":"UnicoreNoClip"
    , "$+g":"UnicoreGodMode"
    , "$+u":"UnicoreUltimate"
    , "$+r":"EasyRefine"
    , "$+c":"EasyCook"
    , "$+1":"E1"
    , "$+2":"E2"
    , "$+3":"E3"
    , "$+4":"E4"
    , "$+5":"E5"
    , "$!1":"Q1"
    , "$!2":"Q2"
    , "$!3":"Q3"
    , "$!4":"Q4"
    , "$!5":"Q5"
    , "$+b":"TakeBitmap"
    , "$F20":"BubbleBreaker"}]

MainHotkeys:=MH.1
for key, mapping in MainHotkeys {
    Hotkey, IfWinActive, ahk_exe GenshinImpact.exe
    Hotkey, % key, % mapping
}
return